### ISSUE TITLE
Feature: Adding options to choose from in the timer screen

### ISSUE THREAD

**Issue by SATVIKSH** [CCExtractor/ultimate_alarm_clock#417] opened 2024-02-02 18:28 UTC
### Description

We can add more options to choose from in the timer screen. For example adding options like 10 minutes etc. This will provide a better user experience. I would like to work on this issue.

**Comment by MarkisDev** [comment] 2024-02-03 09:42
Duplicate of #297. We can continue the conversation there! :)

**Closed** 2024-02-03 09:44 UTC
