### ISSUE TITLE
Feature: Adding an "About" Section with Logo and Links

### ISSUE THREAD

**Issue by andoriyaprashant** [CCExtractor/ultimate_alarm_clock#69] opened 2023-09-13 17:10 UTC
### Description

The current version of the app lacks an "About" section, which is essential for providing users with important information about the app and its creators. The objective is to add an "About" section, including an app logo, a link to our GitHub repository, and a link to the CCextractor organization website. This addition will significantly improve user experience and promote our project and community involvement.

To resolve this issue, I propose the following components for the "About" section:

- **App Logo** 

- **GitHub Link** 

- **CCextractor Organization Website Link**

## Benefits

Adding the "About" section with these elements will achieve the following benefits:

**Improved User Experience:** Users will have easy access to essential information about the app and its development.

**Enhanced Visibility:** Inclusion of the app logo will promote brand recognition.

**Community Engagement:** The GitHub link encourages users to get involved in the development process and contribute to the project.

**Comment by andoriyaprashant** [comment] 2023-09-13 17:17
Hey @MarkisDev  I'd like to work on the "About Section with Logo and Links" (#69) issue. It's a valuable addition to our project. Please consider assigning it to me if you find it suitable.
Thank you

**Comment by MarkisDev** [comment] 2023-09-13 17:40
Sounds like a good idea, I think it would be good to add a navigation drawer and move settings to it as well! :)

**Comment by andoriyaprashant** [comment] 2023-09-13 17:42
Thank you for assigning the task. I will try to work on it as soon as possible, and if I encounter any issues, I will discuss them with you :)

**Comment by MarkisDev** [comment] 2023-09-13 17:43
Please feel free!

**Comment by apexpre-dator** [comment] 2023-09-28 02:41
Hey @MarkisDev, Can I work on this issue?

**Comment by MarkisDev** [comment] 2023-09-28 02:44
I've assigned this to you @apexpre-dator

**Comment by andoriyaprashant** [comment] 2023-09-28 03:36
Hey @MarkisDev  I've actually been quite busy lately due to my college exams, so sorry for the delay. I'll try to open a pull request for this issue as soon as possible.

**Comment by Roshaen** [comment] 2023-09-28 19:29
I would like to work on this issue
Can you assign me? @MarkisDev

**Comment by MarkisDev** [comment] 2023-10-02 21:15
Alright. For the time being, I'm also gonna assign it to @Roshaen :)

**Comment by ShivamMenda** [comment] 2023-10-06 17:47
@MarkisDev If the issue is still open to take up, can I take it up?

**Comment by saurav0523** [comment] 2023-10-08 11:47
hey @MarkisDev can you please assign me this task

**Comment by ShivamMenda** [comment] 2023-10-08 13:12
@MarkisDev Will submit a PR by Wednesday evening for sure.

**Comment by MarkisDev** [comment] 2023-10-23 04:03
Any progress on this? @ShivamMenda

**Comment by ShivamMenda** [comment] 2023-10-23 04:14
@MarkisDev working on it. Figuring out get cli. It worked now. Will finish it asap.

**Comment by MarkisDev** [comment] 2023-10-23 04:30
Alright! Don't hesitate to ask help if you get stuck anywhere :)

**Comment by its-me-abhishek** [comment] 2023-11-12 10:00
Is anyone actively working on resolving this issue? If not, I would like to request to get this issue assigned to me.

**Comment by andoriyaprashant** [comment] 2023-11-12 12:12
Hey @its-me-abhishek I am working on this issue. I am facing some issues on my local device, but I am trying to open a pull request as soon as possible.

**Comment by andoriyaprashant** [comment] 2023-11-13 19:03
Hey @MarkisDev Please review my pull request #145 
Thank you for your support

**Closed** 2023-11-26 17:01 UTC
Labels: enhancement, feat
