### ISSUE TITLE
Bug: Overflow issue when deleting alarm.

### ISSUE THREAD

**Issue by Spiral-Memory** [CCExtractor/ultimate_alarm_clock#513] opened 2024-03-14 14:02 UTC
### Description

There is an overflow issue in the section where we choose an alarm to delete. While debugging, it indicates "Right Overflowed by 32 PIXELS"

### Screenshots

![f654000d-ea9e-4682-95b7-2ba8cf4e0849](https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961432/9f66a415-c9b7-4c3e-9c39-ba486e1165c4)

**Comment by MarkisDev** [comment] 2024-03-26 14:36
I've assigned this to you, the associated PR has some conflicts, please resolve it :)

**Comment by Gaurav-Kushwaha-1225** [comment] 2024-08-16 13:10
Hey @MarkisDev ,
If the issue is not yet resolved, can you assign it to me ??

**Comment by AryanSarafDev** [comment] 2024-08-17 18:54
> Hey @MarkisDev , If the issue is not yet resolved, can you assign it to me ??

@Gaurav-Kushwaha-1225  If you can check if the error is still there? For me, it's working fine. If you can reproduce the error, I will assign this to you or close the issue.

**Comment by Gaurav-Kushwaha-1225** [comment] 2024-08-27 17:17
> > Hey @MarkisDev , If the issue is not yet resolved, can you assign it to me ??
> 
> @Gaurav-Kushwaha-1225 If you can check if the error is still there? For me, it's working fine. If you can reproduce the error, I will assign this to you or close the issue.

- #### I tried to reproduce the error. 
- #### This overflow error not only lies in this page but also on some new pages and features. For example, below are a few examples regarding this. 
#### This has to be resolved.
| ![photo_2024-08-27_22-32-32](https://github.com/user-attachments/assets/ea1e5b7a-ff88-4733-976d-619cdf5ffdea)      | ![photo_2024-08-27_22-32-34](https://github.com/user-attachments/assets/dc283c1c-c49a-4079-a111-20b88fb0cf0c)      | ![photo_2024-08-27_22-32-39](https://github.com/user-attachments/assets/afe47c3a-fd00-4cc0-845f-a8404e54970e)      |
|-----------------------------------------------|----------------------------------------------| ------------------------------------------- |

**Comment by AryanSarafDev** [comment] 2024-08-27 18:35
> > > Hey @MarkisDev , If the issue is not yet resolved, can you assign it to me ??
> > 
> > 
> > @Gaurav-Kushwaha-1225 If you can check if the error is still there? For me, it's working fine. If you can reproduce the error, I will assign this to you or close the issue.
> 
> * #### I tried to reproduce the error.
> * #### This overflow error not only lies in this page but also on some new pages and features. For example, below are a few examples regarding this.
> 
> #### This has to be resolved. @AryanSarafDev
> ![photo_2024-08-27_22-32-32](https://github.com/user-attachments/assets/ea1e5b7a-ff88-4733-976d-619cdf5ffdea)	![photo_2024-08-27_22-32-34](https://github.com/user-attachments/assets/dc283c1c-c49a-4079-a111-20b88fb0cf0c)	![photo_2024-08-27_22-32-39](https://github.com/user-attachments/assets/afe47c3a-fd00-4cc0-845f-a8404e54970e)

You can open an issue and start fixing them if you want. I have merged your theme update.

**Comment by Gaurav-Kushwaha-1225** [comment] 2024-08-27 19:05
Sure, @AryanSarafDev. I'm working on this issue.

**Closed** 2024-08-28 17:14 UTC
Labels: bug
