### ISSUE TITLE
Bug : Alarm not turning off even after completing Maths Challenge

### ISSUE THREAD

**Issue by AnirudhTripathi** [CCExtractor/ultimate_alarm_clock#170] opened 2023-11-27 17:11 UTC
### Description

I have set up the maths challenge on easy mode for two questions , But even after solving the two questions the alarm doesn't turn off. After completion of the time period, the alarm restarts and the maths challenge has to be done again. This feature is not working properly.

**Could you please assign this issue to me?**

### Screenshots

**Screenshots :**

![Screenshot_2023-11-27-22-18-46-664_com example ultimate_alarm_clock](https://github.com/CCExtractor/ultimate_alarm_clock/assets/89296975/fab6671f-f8ac-4fd1-9ec3-44361ddb83d9)

https://github.com/CCExtractor/ultimate_alarm_clock/assets/89296975/d0394869-cdd9-4d0e-b46f-2378fbf8ed1b

**Comment by MarkisDev** [comment] 2023-12-06 17:39
I've assigned this to you, this is not the intended behavior. Please do let me know if you get stuck!

**Comment by Deepanshuigtm** [comment] 2023-12-13 22:39
I am new here and can I fix this issue please

**Comment by Deepanshuigtm** [comment] 2023-12-13 22:39
the problem is in the math_challenge_view.dart file every time we click the _buildDoneButton(), it assign numMathsQuestions back to alarmRecord.numMathsQuestions ( which is the argument that user entered for number of questions )  so one way of fixing it to create a new boolean value and execute that conditional

**Comment by AnirudhTripathi** [comment] 2023-12-14 19:15
@Deepanshuigtm I don't think so that will work as the function isChallengesComplete() from alarm_challenge_controller.dart is not getting called that's why changes should be made in if (alarmRecord.isMathsEnabled) logic
@MarkisDev I have tried multiple ways to implement  if (alarmRecord.isMathsEnabled) using RxDart to implement asynchronous function but it does not show new questions rather old questions is repeated and alarm goes goes off as isChallengesComplete() is called. 

```
if (alarmRecord.isMathsEnabled) {
      rx.Rx.merge([numMathsQuestions.stream, isMathsOngoing.stream])
          .debounceTime(const Duration(milliseconds: 500))
          .listen((dynamic data) {
        if (data is num) {
          num value = data;
          if (value <= 0) {
            isMathsOngoing.value = Status.completed;
            alarmRecord.isMathsEnabled = false;
            Get.back();
            restartTimer();
            isChallengesComplete();
            Future.delayed(const Duration(milliseconds: 500), () {
              newMathsQuestion(); // Introduce a delay before calling the next question
            });
          }
        } else if (data is Status) {
          if (data == Status.initialized) {
            Future.delayed(const Duration(seconds: 1), () {
              isMathsOngoing.value = Status.ongoing;
              restartTimer();
            });
          } else if (data == Status.completed) {
            alarmRecord.isMathsEnabled = false;
            restartTimer();
            isChallengesComplete();
          }
        }
      });

      // Initial call to generate the first question
      newMathsQuestion();
    }
```

**Comment by Deepanshuigtm** [comment] 2023-12-15 00:58
https://github.com/CCExtractor/ultimate_alarm_clock/assets/91874023/9fb1128f-0f9a-4fbc-9302-28659cd7612d

**Comment by Deepanshuigtm** [comment] 2023-12-15 08:55
@MarkisDev please assign this issue to me

**Comment by MarkisDev** [comment] 2023-12-26 14:14
@AnirudhTripathi sorry, i missed this. I don't think it has to be that complicated, the approach suggested by @Deepanshuigtm 
should work. I'm assigning this to him since the same issue had been raised :)

**Comment by Deepanshuigtm** [comment] 2023-12-26 14:44
thank you  @MarkisDev  I will work on this issue and fix this issue 👍

**Closed** 2023-12-29 11:54 UTC
Labels: bug
