### ISSUE TITLE
Bug: The Rings in is not initialized correctly.

### ISSUE THREAD

**Issue by duckcommit** [CCExtractor/ultimate_alarm_clock#531] opened 2024-03-26 10:00 UTC
### Description

If you check the screenshot, you can see that the time is 3:20, alarm is being set for 3:18 and it shows rings in less than one minute. 

The problem is that, once you press the + button to add an alarm, you cancel it, and come back to home, and then again press the + button, the rings in is not getting updated until you touch the timepicker.

Its a good issue, If anyone is looking for issues, maybe you could have a try at it. If no one is interested then I will take it over.

### Screenshots

![Screenshot_20240326_152020](https://github.com/CCExtractor/ultimate_alarm_clock/assets/22213675/a1f7694e-f653-4c0e-b3a8-d32d9550c8f6)

**Comment by MarkisDev** [comment] 2024-03-26 14:39
I've assigned this to you for now. Let me know if you get stuck somewhere :)

**Comment by fierychicken65** [comment] 2024-04-01 06:33
Hey if the issue is still open may I work on it?

**Comment by duckcommit** [comment] 2024-04-01 07:53
Yes, it is open @fierychicken65. Give it a try.

**Comment by fierychicken65** [comment] 2024-04-02 04:36
hey @duckcommit  is the '+' button being used only to **add** more alarms right?
Or is it being used to **update** and **add** alarms?

**Comment by duckcommit** [comment] 2024-04-02 04:40
Yes @fierychicken65 , the + button is used to add the alarm. In order to update the alarm, you can simply click on an existing alarm.

**Comment by fierychicken65** [comment] 2024-04-03 18:03
hey @duckcommit just fixed an issue that wasn't allowing the user to add more alarms just after adding an alarm. Clicking on the + button used to update an alarm instead of creating a new alarm.

https://github.com/CCExtractor/ultimate_alarm_clock/assets/116811583/4ff97a9f-7a2a-49dc-a6f7-b46b77ced6c4

**Comment by fierychicken65** [comment] 2024-04-04 05:35
Hi @duckcommit  so I should raise a seperate issue for this right?

**Comment by duckcommit** [comment] 2024-04-04 05:41
Yes @fierychicken65 . That's exactly what you should do.

**Comment by shreygupta799** [comment] 2024-07-01 18:08
Hey! may I give a try, if the issue is still open

**Comment by AryanSarafDev** [comment] 2024-07-01 18:52
> Hey! may I give a try, if the issue is still open

Hey! @shreygupta799 This issue is fixed. But if you want to try there's a bug which doesn't initialise the values when updating an alarm's time by clicking on it and creates a new duplicate alarm when updated.

**Closed by AryanSarafDev** 2024-07-01 18:52 UTC
Labels: bug, good first issue
