### ISSUE TITLE
Bug: Display "No Alarm Scheduled" Message When No Alarm is Set

### ISSUE THREAD

**Issue by Deepanshuigtm** [CCExtractor/ultimate_alarm_clock#284] opened 2023-12-31 16:13 UTC
### Description

Currently, our application displays the next alarm time as "Next alarm rings in 23 hours 59 minutes" even when no alarm is scheduled by the user. To enhance user experience and provide accurate information:

When there is an alarm scheduled, continue displaying the time until the next alarm rings.
When there is no alarm scheduled, the application should display a message indicating "No alarm scheduled" instead of showing the countdown.

![Simulator Screenshot - iPhone 15 Pro Max - 2023-12-31 at 21 34 54](https://github.com/CCExtractor/ultimate_alarm_clock/assets/91874023/07773c0b-1b4d-4abe-b35c-03b6bc4f24d5)

Expected Behavior:

If an alarm is scheduled, the app should show the time until the next alarm rings.
If no alarm is scheduled, the app should display a clear message stating "No alarm scheduled" instead of showing the countdown.
Proposed Solution:

Implement a check within the application to determine if an alarm is scheduled.
If an alarm is scheduled, continue displaying the countdown to the next alarm.
If no alarm is scheduled, display the message "No alarm scheduled" in place of the countdown.

**Comment by MarkisDev** [comment] 2023-12-31 17:46
I've assigned this to you.

**Comment by keyurgit45** [comment] 2024-01-11 13:25
@MarkisDev Is this issue fixed?

**Comment by Deepanshuigtm** [comment] 2024-01-11 13:39
@keyurgit45 you  can work on this issue if you want to

**Comment by nikkivirtuoso** [comment] 2024-01-12 06:57
please assign this issue to me

**Comment by keyurgit45** [comment] 2024-01-12 12:05
I am not able to reproduce this issue. so not sure if this issue is fixed or not

**Comment by nikkivirtuoso** [comment] 2024-01-12 12:20
its there
<img width="1470" alt="Screenshot 2024-01-12 at 5 49 49 PM" src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/148634283/4a7a1e93-6d11-4245-9d95-f961b1ce5a36">

**Comment by keyurgit45** [comment] 2024-01-12 14:18
okay you can work on this

**Comment by MarkisDev** [comment] 2024-01-13 16:32
I've assigned this to you @nikkivirtuoso

**Comment by keyurgit45** [comment] 2024-01-20 05:59
If this is up for a grab, could be assign this to me? @MarkisDev

**Comment by MarkisDev** [comment] 2024-02-09 01:13
@keyurgit45 I've assigned this to you

**Closed** 2024-02-25 09:45 UTC
Labels: bug, good first issue
