### ISSUE TITLE
Bug: Alarm doesn't go off on iOS

### ISSUE THREAD

**Issue by kvenn** [CCExtractor/ultimate_alarm_clock#150] opened 2023-11-14 17:26 UTC
### Description

1. Install the app
2. Create an alarm (for about 8 hours away)
3. Background the app (but don't force quit)
4. Wait 8 hours

Expected result:
* The alarm goes off

Actual result:
* The alarm never went off

More details
* I haven't tested this on Android, so can't confirm it works there.
* I see you're using foreground_test - their docs indicate it should work, but I don't know if it'll have the precision needed for an alarm app 
	* Docs: https://pub.dev/packages/flutter_foreground_task#baby_chick-ios
	* Issue: https://github.com/Dev-hwang/flutter_foreground_task/issues/18

**Comment by MarkisDev** [comment] 2023-11-26 16:43
I will assign this issue to you since I can't really test for iOS - however, I do know that some functionality is android restricted but this particular one should be working on iOS though. Please do let me know if you get stuck somewhere!

**Comment by MarkisDev** [comment] 2023-12-12 13:28
With #199, alarms would no longer work on iOS. Closing this issue as this is now a duplicate of #224.

**Closed by MarkisDev** 2023-12-12 13:28 UTC
Labels: bug, ios related
