### ISSUE TITLE
Bug: Daily Option check box not working in repeat tile and Options in repeat modal sheet not translated

### ISSUE THREAD

**Issue by Kaps61929** [CCExtractor/ultimate_alarm_clock#399] opened 2024-01-26 07:34 UTC
### Description

When the 'Daily' option checkbox is clicked in the bottom modal sheet of the repeat tile, it does not work, and the options (Daily, Weekdays, Custom)  along with Done button are not translated 

I want to work on this issue, so please consider assigning it to me.

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/115138974/a3e5655b-9b48-4378-a33b-1d33f6c7df42

https://github.com/CCExtractor/ultimate_alarm_clock/assets/115138974/e219da5a-bc1c-4076-a4b5-b477a7c83567

**Comment by superiorsd10** [comment] 2024-01-26 13:16
Hello @Kaps61929 👋

I hope you're doing well. Except for the translation part, this issue is a duplicate of #373.

Thank you,

**Closed** 2024-01-26 14:45 UTC
Labels: bug
