### ISSUE TITLE
Feature: Create a list of frequently used timer

### ISSUE THREAD

**Issue by sagarrajgit** [CCExtractor/ultimate_alarm_clock#377] opened 2024-01-21 12:22 UTC
### Description

Show a list of frequent timers, using which user can quickly set timers of their regular activity like reading, meditation, exercise etc. By default, we will just give 2 or 3 lists of timer and give an add functionality using which user can add their custom timer. Now whenever the user needs to use that timer, just select the timer from the list and press the play button.

If you think this feature might be helpful then I would like to work on this feature.

**Comment by MarkisDev** [comment] 2024-01-21 16:28
Duplicate of #297. We can continue the conversation there, please feel free to put up a PR :)

**Comment by MarkisDev** [comment] 2024-02-03 09:43
Since this is slightly similiar, I'm reopening it.

However, we'll have to make the UI work with proposed #297 as well.

**Comment by sagarrajgit** [comment] 2024-02-03 10:15
so, I can work on this?

**Comment by sagarrajgit** [comment] 2024-02-03 10:29
For #297 we can use the switch screen feature, In the first part it will list of frequent use timer list and on switching it will show a grid of quick timer setter buttons.

**Comment by MarkisDev** [comment] 2024-02-03 10:38
That should do the job.

**Closed** 2024-08-17 18:43 UTC
Labels: enhancement, feat
