### ISSUE TITLE
Feature: Timer/stop watch should also run in notification 

### ISSUE THREAD

**Issue by rkverma2022** [CCExtractor/ultimate_alarm_clock#382] opened 2024-01-22 06:59 UTC
### Description

The Timer/Stopwatch feature should seamlessly runs in the notification bar, ensuring users can effortlessly track time without the need to keep the app open. This enhancement provides a convenient and accessible way for users to monitor elapsed time while performing other tasks on their device. Stay in control of your timers and stopwatches with this streamlined and versatile notification integration.

Hi,

I would like to implement this feature.

**Comment by MarkisDev** [comment] 2024-01-24 13:22
Duplicate of #294. Closing for now, we can continue the conversation there.

**Closed by MarkisDev** 2024-01-24 13:22 UTC

**Comment by MarkisDev** [comment] 2024-01-24 13:26
You can put up a PR for this issue
