### ISSUE TITLE
Bug: Next Alarm Showing Countdown Instead of 'No Upcoming Alarms' on iOS device

### ISSUE THREAD

**Issue by oops-shlok** [CCExtractor/ultimate_alarm_clock#480] opened 2024-03-01 20:32 UTC
### Description

Upon installation of the app on iOS device, the displayed message for the next alarm is "Next alarm in 23 hours 59 minutes," instead of "No Upcoming Alarms" as seen on Android device even when no alarm is scheduled. 

### Screenshots

<img width="441" alt="Screenshot 2024-03-02 at 1 57 25 AM" src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/83498152/756a0d08-f4f2-4b98-a3d3-c006d0f4b1c6">

**Comment by keyurgit45** [comment] 2024-03-02 11:38
Hi @oops-shlok, I noticed the issue you reported already has been fixed in #440. If you have reencountered the issue, please provide the steps to reproduce it.

**Comment by oops-shlok** [comment] 2024-03-02 11:49
> Hi @oops-shlok, I noticed the issue you reported already has been fixed in #440. If you have reencountered the issue, please provide the steps to reproduce it.

Hi @keyurgit45, I saw this bug when i installed the app on iOS device. However, on android device, this bug was not there as it was already fixed in #440 as you mentioned. You can check #481 where I have fixed it for iOS device too. Thanks!

**Comment by keyurgit45** [comment] 2024-03-02 11:58
How is it possible that the issue is fixed on Android but not on iOS?

**Comment by oops-shlok** [comment] 2024-03-02 12:05
> I'm wondering, How is it possible that the issue is fixed on Android but not on iOS?

Indeed. For iOS, this was the error statement appearing in the console before:
<img width="1504" alt="Screenshot 2024-03-02 at 5 31 25 PM" src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/83498152/40808fb7-5cdd-4329-8921-f8a5b3e655c4">

**Comment by MarkisDev** [comment] 2024-03-02 18:20
The missing plugin exception occurs because of #224. There is no native implementation to schedule alarms on iOS.

**Comment by MarkisDev** [comment] 2024-03-10 16:45
Closing this issue since it's an extension of #224.

**Closed by MarkisDev** 2024-03-10 16:45 UTC
Labels: bug, on hold, ios related
