### ISSUE TITLE
Persistent Text Field Values (Label and Note) Across Alarm Creation Dialogs

### ISSUE THREAD

**Issue by davidodejobi** [CCExtractor/ultimate_alarm_clock#538] opened 2024-03-28 07:40 UTC
### Description

Description:
The text fields for the label and note in the alarm creation dialog do not clear after creating an alarm. Consequently, the text entered persists across all created alarms, leading to confusion and inaccurate labeling of alarms.

Steps to Reproduce:

1. Open the alarm creation dialog.
2. Enter a label and note in the designated text fields.
3. Create an alarm.
4. Repeat steps 1-3 to create multiple alarms.
5. Observe that the label and note text fields retain the previously entered text for each subsequent alarm creation.

Expected Behavior:
After creating each alarm, the text fields for the label and note in the dialog should reset to their default state, clearing any previously entered text. This ensures that each new alarm starts with blank label and note fields, allowing users to provide unique information for each alarm.

Actual Behavior:
The text entered in the label and note fields persists across all created alarms. As a result, all alarms end up with the same label and note, which is not the intended behavior.

Possible Solution:
1. Implement a function to reset the label and note text fields in the dialog after creating each alarm.
2. Ensure that the dialog initializes with empty label and note fields for every new alarm creation.
3. Store the label and note data separately for each alarm instance to prevent sharing of text across alarms.
4. Test thoroughly to confirm that the text fields are cleared and that each alarm can have its own unique label and note.

### Screenshots

![CleanShot 2024-03-28 at 07 57 59](https://github.com/CCExtractor/ultimate_alarm_clock/assets/63846399/74afcc9f-89ac-42f1-bc4b-337f1dcf3b30)

**Comment by Gaurav-Kushwaha-1225** [comment] 2024-08-16 12:51
If the issue is resolved, please close it. @davidodejobi

**Closed** 2024-08-16 12:58 UTC
Labels: bug
