### ISSUE TITLE
Feature: Adding a circular progress bar around the timer. 

### ISSUE THREAD

**Issue by SATVIKSH** [CCExtractor/ultimate_alarm_clock#433] opened 2024-02-08 11:52 UTC
### Description

When the timer is  running the user interface is quite unappealing. It can be enhanced if we introduce a circular progress bar  indicator around the time which represents the time left. I would like to  work in this issue.

**Comment by MarkisDev** [comment] 2024-02-09 01:16
This is a duplicate of #299. Feel free to put up a PR but let's continue the conversation there! :)

**Closed by MarkisDev** 2024-02-09 01:16 UTC
