### ISSUE TITLE
Bug: Bottom Navbar does not reset to home upon closing / restarting the app

### ISSUE THREAD

**Issue by its-me-abhishek** [CCExtractor/ultimate_alarm_clock#460] opened 2024-02-26 14:09 UTC
### Steps to reproduce the error: 
Switch across views using the bottom navbar, and then close the app and then restart the app.
- After restarting the app, the home view is set correctly as the view on screen
- But, the navbar shows the previously selected option (that was chosen before closing the app).
- The bottom bar must be set to `Alarm` once we close and restart the app.

I would like to work on this issue if you find this to be acceptable.

### Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/114338679/55e6b4a4-c056-4ac5-8986-de27ce0e9991

**Comment by MarkisDev** [comment] 2024-03-10 16:14
This is a duplicate of #407 so closing it for now.

**Closed by MarkisDev** 2024-03-10 16:14 UTC
Labels: bug
